// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TodoBlazor.Shared.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TodoItem
    {
        /// <summary>
        /// Initializes a new instance of the TodoItem class.
        /// </summary>
        public TodoItem() { }

        /// <summary>
        /// Initializes a new instance of the TodoItem class.
        /// </summary>
        public TodoItem(long id, long listId, string title, bool? isComplete = default(bool?))
        {
            Id = id;
            ListId = listId;
            IsComplete = isComplete;
            Title = title;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "listId")]
        public long ListId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isComplete")]
        public bool? IsComplete { get; set; }

        /// <summary>
        /// The title must be unique within the list it belongs to.
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Title == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Title");
            }
            if (this.Title != null)
            {
                if (this.Title.Length > 125)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Title", 125);
                }
            }
        }
    }
}
